spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ok
mybatis:
  mapper-locations: classpath:mapper/*.xml
